name: sportify
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.4
  firebase_storage: ^11.6.0
  file_picker: ^8.0.0+1
  timezone: ^0.9.2
  encrypt: ^5.0.3
  crypto: ^3.0.3
  http: ^1.1.0
  url_launcher: ^6.2.1
  connectivity_plus: ^5.0.2  # Check internet connection before payment
  image: ^4.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/